#!/bin/bash

set -e

PATH=/var/vcap/packages/postgres-unknown/bin:/var/vcap/packages/postgres-9.6.6/bin:$PATH

pg_restore --user=admin --format=custom --schema=public --clean --dbname=atc $BBR_ARTIFACT_DIRECTORY/atc.backup 
