---
name: concourse-bbr-boshrelease
blobstore:
  provider: s3
  options:
    bucket_name: concourse-bbr-boshrelease
    region: ap-northeast-1
    endpoint: https://s3-ap-northeast-1.amazonaws.com
final_name: bosh-release
