---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: v1.1.3
resources:
- name: repo-dev
  type: git
  source:
    uri: git@github.com:making/concourse-bbr-boshrelease.git
    branch: develop
    private_key: {{github-private-key}}
- name: repo-prod
  type: git
  source:
    uri: git@github.com:making/concourse-bbr-boshrelease.git
    branch: master
    private_key: {{github-private-key}}
- name: repo-version
  type: semver
  source:
    uri: git@github.com:making/concourse-bbr-boshrelease.git
    branch: version
    private_key: {{github-private-key}}
    file: version
    driver: git
- name: gh-release
  type: github-release
  source:
    user: making
    repository: concourse-bbr-boshrelease
    access_token: {{github-access-token}}
- name: utils
  type: git
  source:
    uri: https://github.com/maki-home/concourse-utils
    branch: master
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-webhook-url}}
jobs:
- name: create-boshrelease-dev
  plan:
  - aggregate:
    - get: repo
      resource: repo-dev
      trigger: true
    - get: repo-version
    - get: utils
  - task: create-boshrelease
    file: utils/tasks/boshrelease-create-dev.yml
    params: &S3
      S3_ACCESS_KEY_ID: {{s3-access-key-id}}
      S3_SECRET_ACCESS_KEY: {{s3-secret-access-key}}
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - task: upload-boshrelease
    file: utils/tasks/boshrelease-upload-dev-to-nexus.yml
    params: &NEXUS
      NEXUS_URL: {{nexus-url}}
      NEXUS_USERNAME: {{nexus-username}}
      NEXUS_PASSWORD: {{nexus-password}}
    on_success:
      put: slack-alert
      params: &SLACK_SUCCESS
        channel: '#concourse'
        text: |
          <!here> :white_check_mark: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* succeeded with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!
    on_failure:
      put: slack-alert
      params: &SLACK_FAILURE
        channel: '#concourse'
        text: |
          <!here> :rotating_light: *$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME* failed with build <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$BUILD_NAME>!
- name: merge-develop-to-master
  plan:
  - aggregate:
    - get: repo-other
      resource: repo-prod
    - get: repo-dev
      passed:
      - create-boshrelease-dev
    - get: utils
  - task: merge-develop-to-master
    file: utils/tasks/merge-develop-to-other.yml
    params: &GIT
      GIT_EMAIL: {{git-email}}
      GIT_NAME: {{git-name}}
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - put: repo-prod
    params:
      repository: other-out
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
- name: create-boshrelease
  plan:
  - aggregate:
    - get: repo
      resource: repo-prod
      trigger: true
      passed:
      - merge-develop-to-master
    - get: repo-version
    - get: utils
  - task: create-boshrelease
    file: utils/tasks/boshrelease-create.yml
    params:
      <<: *S3
      <<: *GIT
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - put: repo-prod
    params:
      repository: master-out
      tag: repo-version/number
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - put: gh-release
    params:
      name: repo-version/number
      tag: repo-version/number
      globs:
      - releases/*.tgz
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
    on_success:
      put: slack-alert
      params:
        <<: *SLACK_SUCCESS
- name: bump-to-next-minor-version
  plan:
  - aggregate:
    - get: repo-prod
      passed:
      - create-boshrelease
      trigger: true
    - get: repo-other
      resource: repo-dev
    - get: repo-version
      params:
        bump: minor
    - get: utils
  - task: merge-master-to-develop
    params:
      <<: *GIT
    file: utils/tasks/merge-master-to-other.yml
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - put: repo-dev
    params:
      repository: other-out
    on_success:
      put: slack-alert
      params:
        <<: *SLACK_SUCCESS
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE
  - put: repo-version
    params:
      file: repo-version/number
    on_failure:
      put: slack-alert
      params:
        <<: *SLACK_FAILURE